package chapter16practices;

/* Create a List (try both ArrayList and LinkedList) and fill it using
 * Countries. Sort the list and print it, then apply Collections.shuffle()
 * to the list repeatedly, printing it each time so that you can see how 
 * the shuffle() method randomizes the list differently each time.
 */
import java.util.*;

public class Ex1 {
	public static void main(String[] args) {
		List<String> al = new ArrayList<String>();
		List<String> ll = new LinkedList<String>();
		for(int i = 0; i < Countries.DATA.length; i++) {
			al.add(Countries.DATA[i][0]);
			ll.add(Countries.DATA[i][1]);
		}
		Collections.sort(al);
		Collections.sort(ll);
		System.out.println("Countries: " + al);
		System.out.println("Capitals: " + ll);
		for(int i = 0; i < 2; i++) {
			Collections.shuffle(al);
			Collections.shuffle(ll);
			System.out.println("Countries " + i + ": " + al);
			System.out.println("Capitals " + i + ": " + ll);
		}
		List<String> al2 = new ArrayList<String>();
		List<String> ll2 = new LinkedList<String>();
		for(int i = 0; i < 10; i++) {
			al2.add(Countries.DATA[i][0]);
			ll2.add(Countries.DATA[i][1]);
		}
		for(int i = 0; i < 5; i++) {
			Collections.shuffle(al2);
			Collections.shuffle(ll2);
			System.out.println("Countries " + i + ": " + al2);
			System.out.println("Capitals " + i + ": " + ll2);
			Collections.sort(al2);
			Collections.sort(ll2);
		}
	}
}
/*Output:

Countries: [AFGHANISTAN, ALBANIA, ALGERIA, ANDORRA, ANGOLA, ANTIGUA AND BARBUDA, ARGENTINA, ARMENIA, AUSTRALIA, AUSTRIA, AZERBAIJAN, BAHAMAS, BAHRAIN, BANGLADESH, BARBADOS, BELARUS (BYELORUSSIA), BELGIUM, BELIZE, BENIN, BHUTAN, BISSAU, BOLIVIA, BOSNIA, BOTSWANA, BRAZIL, BRUNEI, BULGARIA, BURKINA FASO, BURUNDI, CAMBODIA, CAMEROON, CANADA, CAPE VERDE, CENTRAL AFRICAN REPUBLIC, CHAD, CHILE, CHINA, COLOMBIA, COMOROS, CONGO, COSTA RICA, COTE D’IVOIR (IVORY COAST), CROATIA, CUBA, CYPRUS, CZECH REPUBLIC, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), DENMARK, DJIBOUTI, DOMINICA, DOMINICAN REPUBLIC, ECUADOR, EGYPT, EL SALVADOR, EQUATORIAL GUINEA, ERITREA, ESTONIA, ETHIOPIA, FIJI, FINLAND, FRANCE, GABON, GEORGIA, GERMANY, GHANA, GREECE, GRENADA, GUATEMALA, GUINEA, GUYANA, HAITI, HERZEGOVINA, HONDURAS, HUNGARY, ICELAND, INDIA, INDONESIA, IRAN, IRAQ, IRELAND, ISRAEL, ITALY, JAMAICA, JAPAN, JORDAN, KAZAKSTAN, KENYA, KIRIBATI, KUWAIT, KYRGYZSTAN, LAOS, LATVIA, LEBANON, LESOTHO, LIBERIA, LIBYA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MACEDONIA, MADAGASCAR, MALAWI, MALAYSIA, MALI, MALTA, MARSHALL ISLANDS, MAURITANIA, MAURITIUS, MEXICO, MICRONESIA, MOLDOVA, MONACO, MONGOLIA, MONTENEGRO, MOROCCO, MOZAMBIQUE, MYANMAR (BURMA), NAMIBIA, NAURU, NEPAL, NEVIS, NEW ZEALAND, NICARAGUA, NIGER, NIGERIA, NORTH KOREA, NORWAY, OMAN, PAKISTAN, PALAU, PANAMA, PAPUA NEW GUINEA, PARAGUAY, PERU, PHILIPPINES, POLAND, PORTUGAL, QATAR, ROMANIA, RUSSIA, RWANDA, SAN MARINO, SAO TOME E PRINCIPE, SAUDI ARABIA, SENEGAL, SERBIA, SEYCHELLES, SIERRA LEONE, SINGAPORE, SLOVAKIA, SLOVENIA, SOLOMON ISLANDS, SOMALIA, SOUTH AFRICA, SOUTH KOREA, SPAIN, SRI LANKA, ST. KITTS, ST. LUCIA, ST. VINCENT AND THE GRENADINES, SUDAN, SURINAME, SWAZILAND, SWEDEN, SWITZERLAND, SYRIA, TAIWAN (REPUBLIC OF CHINA), TAJIKISTAN, TANZANIA, THAILAND, THE GAMBIA, THE MALDIVES, THE NETHERLANDS, TOGO, TONGA, TRINIDAD AND TOBAGO, TUNISIA, TURKEY, TURKMENISTAN, TUVALU, UGANDA, UKRAINE, UNITED ARAB EMIRATES, UNITED KINGDOM, UNITED STATES OF AMERICA, URUGUAY, UZBEKISTAN, VANUATU, VATICAN CITY, VENEZUELA, VIETNAM, WESTERN SAMOA, YEMEN, ZAMBIA, ZIMBABWE]
Capitals: [-, -, ---, < Port-Vila, Abu Dhabi, Abuja, Accra, Addis Ababa, Algiers, Alma-Ata, Almaty, Amman, Amsterdam, Andorra la Vella, Ankara, Antananarivo, Apia, Ashkabad, Asmara, Asuncion, Athens, Baghdad, Bairiki, Baku, Bamako, Bandar Seri Begawan, Bangkok, Bangui, Banjul, Basseterre, Beijing, Beirut, Belgrade, Belmopan, Berlin, Berne, Bissau, Bogota, Brasilia, Bratislava, Brazzaville, Bridgetown, Brussels, Bucharest, Budapest, Buenos Aires, Bujumbura, Cairo, Canberra, Caracas, Castries, Chisinau, Colombo, Conakry, Copenhagen, Dakar, Dalap-Uliga-Darrit, Damascus, Dhaka, Dijibouti, Dodoma, Doha, Dublin, Dushanbe, Fongafale, Freetown, Gaberone, Georgetown, Guatemala City, Hanoi, Harare, Havana, Helsinki, Honaira, Islamabad, Jakarta, Jerusalem, Kabul, Kampala, Katmandu, Khartoum, Kigali, Kingston, Kingstown, Kinshasa, Koror, Kuala Lumpur, Kuwait City, Kyiv, Libreville, Lilongwe, Lima, Lisbon, Ljuijana, Lome, London, Luanda, Lusaka, Luxembourg, Madrid, Malabo, Male, Managua, Manama, Manila, Maputo, Maseru, Mbabane, Mexico City, Minsk, Mogadishu, Monaco, Monrovia, Montevideo, Moroni, Moscow, Muscat, Nairobi, Nassau, New Delhi, Niamey, Nicosia, Nouakchott, Nuku’alofa, N’djamena, Oslo, Ottawa, Ouagadougou, Palikir, Panama City, Paramaribo, Paris, Phnom Penh, Podgorica, Port Louis, Port Moresby, Port of Spain, Port-au-Prince, Porto-Novo, Prague, Praia, Pretoria/Cape Town, P’yongyang, Quito, Rabat, Rangoon, Reykjavik, Riga, Riyadh, Rome, Roseau, Saint George’s, Saint John’s, San Jose, San Marino, San Salvador, Sana’a, Santiago, Santo Domingo, Sao Tome, Sarajevo, Seoul, Singapore, Skopje, Sofia, Stockholm, Sucre (legal)/La Paz(administrative), Suva, Taipei, Tallinn, Tashkent, Tbilisi, Tegucigalpa, Tehran, Thimphu, Tirana, Tokyo, Tripoli, Tunis, Ulan Bator, Vaduz, Valletta, Victoria, Vienna, Vientiane, Vilnius, Warsaw, Washington, D.C., Wellington, Windhoek, Yamoussoukro, Yaounde, Yaren, Yerevan, Zagreb]
Countries 0: [ANDORRA, ITALY, BOLIVIA, COTE D’IVOIR (IVORY COAST), SRI LANKA, DOMINICA, CHAD, LIBERIA, PHILIPPINES, CUBA, LIBYA, LESOTHO, ARMENIA, MADAGASCAR, TANZANIA, PARAGUAY, ALBANIA, BAHAMAS, NEPAL, SPAIN, GUINEA, MALTA, ZAMBIA, RWANDA, HONDURAS, FIJI, PORTUGAL, AFGHANISTAN, BRAZIL, VIETNAM, EGYPT, BOTSWANA, JAPAN, VANUATU, COLOMBIA, PANAMA, SAN MARINO, UNITED KINGDOM, SURINAME, GRENADA, SOUTH KOREA, CENTRAL AFRICAN REPUBLIC, GABON, ECUADOR, ALGERIA, LEBANON, BOSNIA, GEORGIA, MICRONESIA, KIRIBATI, KYRGYZSTAN, BRUNEI, EQUATORIAL GUINEA, SOUTH AFRICA, MONGOLIA, CAPE VERDE, HERZEGOVINA, BAHRAIN, SOLOMON ISLANDS, GUYANA, SENEGAL, SERBIA, LAOS, UKRAINE, GREECE, THE MALDIVES, VATICAN CITY, CZECH REPUBLIC, BULGARIA, DENMARK, PAKISTAN, BELGIUM, SWITZERLAND, URUGUAY, MAURITIUS, SINGAPORE, CYPRUS, ANTIGUA AND BARBUDA, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), CROATIA, JORDAN, BURKINA FASO, CHINA, GERMANY, HUNGARY, ST. VINCENT AND THE GRENADINES, MONTENEGRO, BISSAU, KENYA, BHUTAN, COSTA RICA, WESTERN SAMOA, ERITREA, YEMEN, THE NETHERLANDS, SLOVAKIA, ARGENTINA, VENEZUELA, TURKMENISTAN, SLOVENIA, BELARUS (BYELORUSSIA), NIGER, SWEDEN, INDONESIA, PALAU, NAURU, SWAZILAND, TOGO, CAMBODIA, TURKEY, MYANMAR (BURMA), MOROCCO, HAITI, COMOROS, CAMEROON, DJIBOUTI, LITHUANIA, JAMAICA, BENIN, LATVIA, UZBEKISTAN, KAZAKSTAN, SYRIA, MALAYSIA, ZIMBABWE, SIERRA LEONE, MOLDOVA, ROMANIA, ST. LUCIA, TAIWAN (REPUBLIC OF CHINA), NICARAGUA, DOMINICAN REPUBLIC, BELIZE, SOMALIA, TONGA, THAILAND, ST. KITTS, INDIA, AZERBAIJAN, BANGLADESH, QATAR, MACEDONIA, FINLAND, SAUDI ARABIA, FRANCE, MALI, SAO TOME E PRINCIPE, PAPUA NEW GUINEA, MONACO, EL SALVADOR, MEXICO, BURUNDI, IRAN, NIGERIA, OMAN, MAURITANIA, LIECHTENSTEIN, BARBADOS, ANGOLA, UNITED STATES OF AMERICA, NORWAY, SUDAN, TRINIDAD AND TOBAGO, POLAND, NAMIBIA, IRELAND, AUSTRIA, CANADA, MOZAMBIQUE, UGANDA, LUXEMBOURG, GHANA, THE GAMBIA, IRAQ, RUSSIA, MARSHALL ISLANDS, ESTONIA, PERU, NEVIS, SEYCHELLES, GUATEMALA, TUNISIA, ETHIOPIA, KUWAIT, ICELAND, UNITED ARAB EMIRATES, TAJIKISTAN, CHILE, TUVALU, NEW ZEALAND, AUSTRALIA, MALAWI, NORTH KOREA, ISRAEL, CONGO]
Capitals 0: [Managua, Port Louis, Nicosia, Helsinki, Katmandu, Lusaka, Fongafale, Nassau, Dalap-Uliga-Darrit, Maputo, Nouakchott, Port Moresby, Wellington, Dijibouti, Sucre (legal)/La Paz(administrative), Vaduz, Quito, Tegucigalpa, -, Asmara, Bamako, Luxembourg, Washington, D.C., Bogota, Alma-Ata, Vilnius, Abu Dhabi, Windhoek, Stockholm, Seoul, Dodoma, Kingstown, Pretoria/Cape Town, Ankara, Beijing, Prague, Sarajevo, Canberra, Montevideo, Amman, Mbabane, Kingston, Ouagadougou, Amsterdam, Kuwait City, Maseru, Bangui, Havana, Santiago, Bujumbura, Saint George’s, Podgorica, Copenhagen, Madrid, Malabo, -, Monrovia, Warsaw, Male, Thimphu, Mexico City, Riga, Rabat, Belmopan, Lima, Dublin, Sofia, Apia, Paramaribo, Valletta, Tallinn, Abuja, San Salvador, Dushanbe, Rangoon, Gaberone, Caracas, Oslo, Tbilisi, Koror, Athens, Guatemala City, Khartoum, Lome, Bratislava, Dhaka, Taipei, Sana’a, Porto-Novo, Damascus, Bissau, Budapest, P’yongyang, Port-au-Prince, Tripoli, Brazzaville, Port of Spain, Bridgetown, Yaounde, Dakar, Kinshasa, Moroni, Brussels, Niamey, Accra, Castries, Algiers, Suva, Tashkent, San Marino, Tunis, Yaren, Bairiki, Vienna, Tirana, Lisbon, Panama City, Baku, Tokyo, Buenos Aires, Manama, Almaty, Yerevan, Lilongwe, Minsk, Berne, Paris, Kuala Lumpur, London, Victoria, Baghdad, Colombo, Kyiv, Reykjavik, Phnom Penh, ---, Bandar Seri Begawan, Belgrade, Monaco, Kigali, Antananarivo, N’djamena, Muscat, Vientiane, Cairo, Andorra la Vella, Berlin, Kampala, Yamoussoukro, Beirut, Doha, Chisinau, Harare, Nairobi, Hanoi, Roseau, Ljuijana, Singapore, Santo Domingo, San Jose, < Port-Vila, Ulan Bator, Skopje, Conakry, Ashkabad, Freetown, Islamabad, Banjul, Honaira, Brasilia, Kabul, Nuku’alofa, Libreville, Jerusalem, Palikir, Sao Tome, Rome, Saint John’s, Moscow, Ottawa, New Delhi, Bucharest, Manila, Zagreb, Asuncion, Tehran, Georgetown, Riyadh, Addis Ababa, Mogadishu, Luanda, Jakarta, Praia, Bangkok, Basseterre]
Countries 1: [MOROCCO, KYRGYZSTAN, HERZEGOVINA, BOTSWANA, TOGO, ICELAND, NEPAL, CHAD, CANADA, SYRIA, MALAWI, MALAYSIA, GUYANA, TAJIKISTAN, KUWAIT, DJIBOUTI, CAMEROON, ANDORRA, FRANCE, PARAGUAY, HONDURAS, UNITED ARAB EMIRATES, SOLOMON ISLANDS, NEW ZEALAND, DOMINICA, LUXEMBOURG, MARSHALL ISLANDS, CONGO, KENYA, SEYCHELLES, GREECE, MAURITANIA, CAPE VERDE, AFGHANISTAN, FINLAND, THE MALDIVES, QATAR, MOZAMBIQUE, VIETNAM, EQUATORIAL GUINEA, URUGUAY, ANTIGUA AND BARBUDA, BAHAMAS, LESOTHO, JORDAN, ALBANIA, CAMBODIA, TURKMENISTAN, TRINIDAD AND TOBAGO, LIBERIA, NIGERIA, ST. LUCIA, THE NETHERLANDS, NAURU, ETHIOPIA, BULGARIA, TURKEY, ROMANIA, SOMALIA, COTE D’IVOIR (IVORY COAST), FIJI, NIGER, BAHRAIN, ST. VINCENT AND THE GRENADINES, MACEDONIA, NAMIBIA, MEXICO, GABON, CYPRUS, GERMANY, OMAN, SOUTH AFRICA, VENEZUELA, VATICAN CITY, LATVIA, GUINEA, ZIMBABWE, SURINAME, TANZANIA, SPAIN, BELARUS (BYELORUSSIA), NORWAY, BOLIVIA, COSTA RICA, BISSAU, ERITREA, IRAQ, EL SALVADOR, SAN MARINO, KIRIBATI, JAMAICA, KAZAKSTAN, RUSSIA, DOMINICAN REPUBLIC, SWITZERLAND, VANUATU, RWANDA, SAO TOME E PRINCIPE, BELGIUM, BURKINA FASO, GRENADA, BHUTAN, MONTENEGRO, SERBIA, UGANDA, UKRAINE, MICRONESIA, GHANA, IRAN, TUVALU, THE GAMBIA, WESTERN SAMOA, LEBANON, TONGA, ISRAEL, MOLDOVA, LAOS, TAIWAN (REPUBLIC OF CHINA), ST. KITTS, NICARAGUA, UNITED KINGDOM, JAPAN, BANGLADESH, SAUDI ARABIA, YEMEN, BURUNDI, BARBADOS, PERU, PALAU, BENIN, INDIA, LITHUANIA, NORTH KOREA, POLAND, PAKISTAN, AZERBAIJAN, GEORGIA, ZAMBIA, LIECHTENSTEIN, MONACO, PHILIPPINES, SLOVAKIA, IRELAND, SINGAPORE, MAURITIUS, CHILE, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), SRI LANKA, ESTONIA, MALTA, SENEGAL, PORTUGAL, PAPUA NEW GUINEA, ITALY, EGYPT, MALI, LIBYA, MADAGASCAR, BOSNIA, SLOVENIA, ARGENTINA, TUNISIA, INDONESIA, SWEDEN, NEVIS, UZBEKISTAN, CHINA, UNITED STATES OF AMERICA, SUDAN, MONGOLIA, AUSTRALIA, MYANMAR (BURMA), AUSTRIA, CENTRAL AFRICAN REPUBLIC, SWAZILAND, ANGOLA, THAILAND, BRUNEI, CZECH REPUBLIC, HAITI, ALGERIA, COLOMBIA, DENMARK, BELIZE, GUATEMALA, SOUTH KOREA, BRAZIL, PANAMA, ARMENIA, ECUADOR, CROATIA, SIERRA LEONE, CUBA, COMOROS, HUNGARY]
Capitals 1: [N’djamena, Kingston, Georgetown, Tallinn, Buenos Aires, Kuala Lumpur, P’yongyang, Islamabad, Taipei, San Salvador, Madrid, Dhaka, Palikir, Ljuijana, Banjul, Dakar, Tokyo, Accra, Malabo, Bangkok, Moroni, Moscow, Praia, Copenhagen, Vienna, Conakry, Washington, D.C., Sofia, Porto-Novo, Alma-Ata, Kampala, Rome, Monrovia, Male, Hanoi, London, Mbabane, < Port-Vila, ---, Bucharest, Gaberone, Almaty, Dodoma, Rabat, Tripoli, Honaira, -, Basseterre, Baghdad, Lusaka, Kingstown, Vaduz, Prague, Santiago, Mexico City, Beijing, Brazzaville, Rangoon, Budapest, Port-au-Prince, Paramaribo, San Marino, Abuja, Addis Ababa, Berlin, Fongafale, Cairo, San Jose, Thimphu, Lisbon, Nairobi, Panama City, Asmara, Castries, Vilnius, Ashkabad, Tegucigalpa, Wellington, Bamako, Yamoussoukro, Yaounde, Port Louis, Lima, Lome, Riga, Bangui, Doha, Havana, Nicosia, Monaco, Libreville, Warsaw, Dushanbe, Bujumbura, Algiers, Brussels, Nassau, Oslo, Minsk, Suva, Ouagadougou, Jerusalem, Harare, Luanda, Managua, Brasilia, New Delhi, Manila, Amsterdam, Kabul, Bridgetown, Bairiki, Abu Dhabi, Maputo, Bogota, Belmopan, Stockholm, Sao Tome, Lilongwe, Tunis, Quito, Port Moresby, Manama, Ankara, Ottawa, Muscat, Roseau, Paris, Baku, Nouakchott, Tehran, Tashkent, Reykjavik, Zagreb, Colombo, Phnom Penh, Dalap-Uliga-Darrit, -, Mogadishu, Seoul, Freetown, Damascus, Nuku’alofa, Bandar Seri Begawan, Skopje, Yaren, Kigali, Tirana, Amman, Maseru, Port of Spain, Berne, Bratislava, Kyiv, Luxembourg, Belgrade, Sana’a, Yerevan, Singapore, Antananarivo, Helsinki, Katmandu, Athens, Riyadh, Sucre (legal)/La Paz(administrative), Windhoek, Kinshasa, Pretoria/Cape Town, Podgorica, Guatemala City, Andorra la Vella, Saint George’s, Canberra, Niamey, Valletta, Koror, Dijibouti, Saint John’s, Dublin, Victoria, Khartoum, Asuncion, Chisinau, Montevideo, Ulan Bator, Beirut, Apia, Tbilisi, Bissau, Jakarta, Santo Domingo, Vientiane, Kuwait City, Caracas, Sarajevo]
Countries 0: [CHAD, ANGOLA, CENTRAL AFRICAN REPUBLIC, BOTSWANA, CAPE VERDE, CAMEROON, BURUNDI, ALGERIA, BENIN, BURKINA FASO]
Capitals 0: [Bujumbura, Porto-Novo, Algiers, Praia, Ouagadougou, Bangui, Yaounde, Gaberone, N’djamena, Luanda]
Countries 1: [BURKINA FASO, CAPE VERDE, CAMEROON, CHAD, BURUNDI, BENIN, CENTRAL AFRICAN REPUBLIC, ANGOLA, ALGERIA, BOTSWANA]
Capitals 1: [Yaounde, N’djamena, Algiers, Gaberone, Bangui, Praia, Luanda, Ouagadougou, Bujumbura, Porto-Novo]
Countries 2: [CHAD, BOTSWANA, ALGERIA, BURKINA FASO, BURUNDI, CENTRAL AFRICAN REPUBLIC, CAPE VERDE, CAMEROON, BENIN, ANGOLA]
Capitals 2: [Porto-Novo, Yaounde, Bangui, Praia, Bujumbura, Gaberone, Algiers, Luanda, Ouagadougou, N’djamena]
Countries 3: [BENIN, CHAD, BURKINA FASO, BOTSWANA, BURUNDI, CAPE VERDE, CENTRAL AFRICAN REPUBLIC, ANGOLA, CAMEROON, ALGERIA]
Capitals 3: [Ouagadougou, Praia, Bangui, Porto-Novo, Gaberone, Yaounde, Bujumbura, N’djamena, Luanda, Algiers]
Countries 4: [BURKINA FASO, BURUNDI, CHAD, ALGERIA, CAPE VERDE, CAMEROON, ANGOLA, CENTRAL AFRICAN REPUBLIC, BENIN, BOTSWANA]
Capitals 4: [Bangui, Porto-Novo, Gaberone, N’djamena, Luanda, Praia, Ouagadougou, Bujumbura, Yaounde, Algiers]
 
 */